### ISSUE TITLE
bug: wrong zone selected when apex listener host in gateway

### ISSUE THREAD

**Issue by maleck13** [Kuadrant/dns-operator#213]
issue here is that the domain is an apex domain but the controller ignores this and finds a sub zone if present 

The controller will fail with an error around the zone id and records . The controller selects the hcapapps.net zone rather than the specific.hcpapps.net zone

```
[Id: /hostedzone/Z06040283U9V7KNOSLFVI] when submitting change batch","controller":"dnsrecord","controllerGroup":"kuadrant.io","controllerKind":"DNSRecord","DNSRecord":{"name":"external-private","namespace":"demo"},"namespace":"demo","name":"external-private","reconcileID":"ff9b9e6d-2c2e-4991-bd7b-80d7f1442924","rootHost":"private.hcpapps.net","ownerID":"18mfjtpq","zoneID":"/hostedzone/Z06040283U9V7KNOSLFVI","zoneDomainName":"hcpapps.net","region":null,"error":"InvalidChangeBatch: [RRSet of type CNAME with DNS name private.hcpapps.net. is not permitted as it conflicts with other records with the same DNS name in zone hcpapps.net.]
```

Gateway:

```
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: external
  namespace: demo
spec:
  gatewayClassName: istio
  listeners:
  - allowedRoutes:
      namespaces:
        from: Same
    hostname: '*.demos.kuadrant.io'
    name: api
    port: 443
    protocol: HTTPS
    tls:
      certificateRefs:
      - group: ""
        kind: Secret
        name: api-external-tls
      mode: Terminate
  - allowedRoutes:
      namespaces:
        from: Same
    hostname: specific.hcpapps.net
    name: private
    port: 80
    protocol: HTTP
```

HTTPRoute
```
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: test
  namespace: demo
spec:
  hostnames:
  - specific.hcpapps.net
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: external
    namespace: demo
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: toystore
      port: 80
      weight: 1
    matches:
    - path:
        type: PathPrefix
        value: /

```
