### ISSUE TITLE
Support wildcard hosts in CoreDNS

### ISSUE THREAD

**Issue by maleck13** [Kuadrant/dns-operator#434]
**What**

Currently wildcard hosts don't work as expected with a Core DNS provider. We need to address this as a wildcard is often used as a gateway host

**Comment by mikenairn** [comment]
The current implementation is only ever looking for records that exactly match the root host, querying only that host and a couple of others for weight and geo txt records. This works fine if you only have a DNSRecord that contains endpoints that are expected to be in the chain of records that would be returned when querying the root host.

This will work:
```yaml
rootHost: k.example.com
endpoints:
  - dnsName: k.example.com
    recordTTL: 300
    recordType: CNAME
    targets:
      - klb.k.example.com
  - dnsName: klb.k.example.com
    recordTTL: 60
    recordType: A
    targets:
      - 81.17.23.2
 ``` 

returning both endpoints since they will all be returned when querying "k.example.com".

This will not:

```yaml
rootHost: k.example.com
endpoints:
  - dnsName: k.example.com
    recordTTL: 300
    recordType: CNAME
    targets:
      - klb.k.example.com
  - dnsName: klb.k.example.com
    recordTTL: 60
    recordType: A
    targets:
      - 81.17.23.20
  - dnsName: foo.k.example.com
    recordTTL: 60
    recordType: A
    targets:
      - 127.0.0.1
```

Since " foo.k.example.com" even though it has the correct root host, is not part of the chain when querying "k.example.com"

The problem here is northing really to do with wildcard hosts, they actually work fine, only the [test](https://github.com/Kuadrant/dns-operator/blob/main/test/e2e/single_record_test.go#L81) includes additional endpoints that won't be returned for the reasons above.
