### ISSUE TITLE
bug: wildcards records are not added as expected

### ISSUE THREAD

**Issue by maleck13** [Kuadrant/dns-operator#88]
when using a wildcard hostname with distributed DNS, the DNSRecord structure looks correct but it differs from what is actually added to route53

to see this issue create a loadbalanced dns policy and/or resulting dns record. 

You will see it has the right endpoints

```
endpoints:
    - dnsName: '*.managed.hcpapps.net'
      recordTTL: 300
      recordType: CNAME
      targets:
        - klb.managed.hcpapps.net
    - dnsName: default.klb.managed.hcpapps.net
      providerSpecific:
        - name: weight
          value: '120'
      recordTTL: 60
      recordType: CNAME
      setIdentifier: a6e65a17553d94a18a87ac384f734e8b-1159838119.us-east-1.elb.amazonaws.com
      targets:
        - >-
          a6e65a17553d94a18a87ac384f734e8b-1159838119.us-east-1.elb.amazonaws.com
    - dnsName: klb.managed.hcpapps.net
      providerSpecific:
        - name: geo-code
          value: '*'
      recordTTL: 300
      recordType: CNAME
      setIdentifier: default
      targets:
        - default.klb.managed.hcpapps.net
      
```

but in AWS it looks different 

![Uploading Screenshot 2024-04-22 at 14.08.49.png…]()
